spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/carddb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

server:
  port: ${PORT:8080}

security:
  jwt:
    secret: ${JWT_SECRET:VGhpcy1pcy1hLWxvbmcgMzItYnl0ZS1zZWNyZXQtZm9yLUhTMjU2IS0tLXNlY3JldA==}
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}

springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /swagger-ui
