services:
  app:
    image: ${REGISTRY_IMAGE:-ghcr.io/yourorg/card-management}:${TAG:-latest}
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - ./env/${ENV:-dev}.env
    depends_on:
      - db
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: cards
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - cards_pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  cards_pg:
