services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./env/dev.env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: cards
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - cards_pg:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  cards_pg:
