name: Build & Push Image (Buildpacks)

on:
  push:
    branches: [ "main" ]

jobs:
  build-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Build jar
        run: ./gradlew clean build -x test

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build OCI image with Buildpacks
        run: |
          ./gradlew bootBuildImage \
            --imageName ghcr.io/${{ github.repository }}:latest \
            -PBP_JVM_VERSION=17

      - name: Push image
        run: docker push ghcr.io/${{ github.repository }}:latest
